{ lib, writeTextDir }:
{ enable ? true
, colors ? {
    foreground = "#ffffff";
    background = "#000000";
  }
, cursor ? {
    size = 24;
    theme = "Adwaita";
    hideTimeout = 5000;
    showWhenTyping = "enable";
  }
, font ? {
    name = "monospace";
    size = 12;
  }
, keybindings ? {
    settings = "s";
    display = "x";
    wifi = "y";
    bluetooth = "u";
    files = "Shift+f";
    exitApp = "Shift+q";
    killApp = "Alt+q";
    reload = "Shift+c";
    refresh = "Shift+r";
    logout = "Shift+e";
    reboot = "Shift+b";
    shutdown = "Shift+p";
    sleep = "Shift+s";
    launcherApp = "space";
    launcherCmd = "Shift+space";
    help = "question";
    launcherWindow = "Ctrl+space";
    fileSearch = "Alt+space";
    lookSelector = "Alt+l";
  }
, bar ? {
    position = "bottom";
    font = "monospace";
    separatorChar = " ";
    mode = "dock";
    workspaceMinWidth = 36;
  }
, extraConfig ? ""
}:

let
  xresourcesContent = ''
    ! Regolith Xresources file - Generated by Nix

    ! Colors
    *.foreground: ${colors.foreground}
    *.background: ${colors.background}
    
    ! Cursor settings
    Xcursor.size: ${toString cursor.size}
    Xcursor.theme: ${cursor.theme}
    
    ! Font settings
    *.font: ${font.name}-${toString font.size}
    
    ! Window manager settings
    wm.hide_cursor.timout: ${toString cursor.hideTimeout}
    wm.hide_cursor.show_when_typing: ${cursor.showWhenTyping}
    
    ! Keybindings
    wm.binding.settings: ${keybindings.settings}
    wm.binding.display: ${keybindings.display}
    wm.binding.wifi: ${keybindings.wifi}
    wm.binding.bluetooth: ${keybindings.bluetooth}
    wm.binding.files: ${keybindings.files}
    wm.binding.exit_app: ${keybindings.exitApp}
    wm.binding.kill_app: ${keybindings.killApp}
    wm.binding.reload: ${keybindings.reload}
    wm.binding.refresh: ${keybindings.refresh}
    wm.binding.logout: ${keybindings.logout}
    wm.binding.reboot: ${keybindings.reboot}
    wm.binding.shutdown: ${keybindings.shutdown}
    wm.binding.sleep: ${keybindings.sleep}
    wm.binding.launcher.app: ${keybindings.launcherApp}
    wm.binding.launcher.cmd: ${keybindings.launcherCmd}
    wm.binding.help: ${keybindings.help}
    wm.binding.launcher.window: ${keybindings.launcherWindow}
    wm.binding.file_search: ${keybindings.fileSearch}
    wm.binding.look_selector: ${keybindings.lookSelector}
    
    ! Bar configuration
    wm.bar.position: ${bar.position}
    wm.bar.font: ${bar.font}
    wm.bar.separatorchar: ${bar.separatorChar}
    wm.bar.mode: ${bar.mode}
    wm.bar.workspace_min_width: ${toString bar.workspaceMinWidth}
    
    ! Extra configuration
    ${extraConfig}
  '';

in writeTextDir "share/regolith/regolith/config" xresourcesContent 