name: "Test"
on:
  pull_request:
  push:
jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix flake check
    - run: echo "The following changes do not evaluate as proper nix expressions - https://nix.dev/manual/nix/2.17/command-ref/new-cli/nix3-flake-check"
    
  ilia:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#ilia

  rofication:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#rofication

  regolith-powerd-inputd-displayd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#regolith-powerd
    - run: nix build .#regolith-inputd
    - run: nix build .#regolith-displayd
    - run: nix build .#libtrawldb

  sway-regolith:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#sway-regolith

  trawl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#trawl

  xrescat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#xrescat
    
  regolith-session:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#regolith-session
    
  status-bar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#i3-swap-focus
    - run: nix build .#i3status-rs
    - run: nix build .#i3xrocks

  regolith-config-styles-essentials:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#regolith-wm-config
    - run: nix build .#regolith-xresources
    - run: nix build .#regolith-ftue
    - run: nix build .#remontoire
    - run: nix build .#regolith-styles
    - run: nix build .#regolith-look-default
    - run: nix build .#regolith-look-extra
    